import { CircleDollarSign, Landmark, Plus, TrendingUp } from "lucide-react";
import { initialBuildingsForApp } from "@/lib/initial-data";
import { compactBrl } from "@/lib/format";

export default function PatrimonioPage() {
  const totalValue = initialBuildingsForApp.reduce((total, building) => total + building.value, 0);
  const totalUnits = initialBuildingsForApp.reduce((total, building) => total + building.units, 0);
  return <div className="content"><div className="page-heading"><div><div className="eyebrow"><Landmark size={13} /> Visão consolidada</div><h1>Patrimônio</h1><p className="subtitle">Todos os imóveis e valores presentes na planilha enviada.</p></div><button className="button button-primary"><Plus size={15} /> Adicionar ativo</button></div><div className="metrics"><div className="metric-card"><div className="metric-top"><span>Valor total</span><span className="metric-icon"><CircleDollarSign size={15} /></span></div><div className="metric-value">{compactBrl(totalValue)}</div><div className="metric-foot positive">Avaliação da planilha</div></div><div className="metric-card"><div className="metric-top"><span>Prédios / grupos</span><span className="metric-icon">{initialBuildingsForApp.length}</span></div><div className="metric-value">{initialBuildingsForApp.length}</div><div className="metric-foot">{totalUnits} unidades</div></div><div className="metric-card"><div className="metric-top"><span>Imóveis</span><span className="metric-icon"><Landmark size={15} /></span></div><div className="metric-value">{compactBrl(totalValue)}</div><div className="metric-foot">63 registros importados</div></div><div className="metric-card"><div className="metric-top"><span>Fonte dos dados</span><span className="metric-icon"><TrendingUp size={15} /></span></div><div className="metric-value">XLSX</div><div className="metric-foot positive">Dados iniciais carregados</div></div></div><div className="panel"><div className="panel-heading"><div><h2>Ativos imobiliários</h2><p>Prédios e propriedades independentes</p></div></div><div className="building-list">{initialBuildingsForApp.map((building) => <div className="building-row" key={building.id}><div className="building-thumb" /><div className="building-info"><strong>{building.name}</strong><small>Imóvel · {building.city}, {building.state}</small></div><div className="building-value"><strong>{compactBrl(building.value)}</strong><small className="positive">{building.units} unidades</small></div></div>)}</div></div></div>;
}
