import Link from "next/link";
import { ArrowLeft, BedDouble, CalendarDays, ChevronRight, FileText, Plus, Ruler, Users, WalletCards } from "lucide-react";
import { demoUnits } from "@/lib/demo-data";
import { brl, compactBrl } from "@/lib/format";

const statusLabel: Record<string, string> = { alugado: "Alugado", vago: "Vago", manutencao: "Manutenção" };

export default function BuildingPage() {
  return <div className="content"><Link href="/imoveis" className="breadcrumb" style={{ marginBottom: 25, display: "inline-flex" }}><ArrowLeft size={13} /> Imóveis <span>/</span> Edifício Cardoso</Link><div className="page-heading"><div><div className="eyebrow"><span className="tag">ATIVO</span> São Paulo · SP</div><h1>Edifício Cardoso</h1><p className="subtitle">Rua Harmonia, 128 · Vila Madalena · Atualizado hoje às 09:42</p></div><div style={{ display: "flex", gap: 9 }}><button className="button button-ghost"><FileText size={14} /> Documentos</button><button className="button button-primary"><Plus size={15} /> <span>Adicionar unidade</span></button></div></div>
    <section className="metrics"><div className="metric-card"><div className="metric-top"><span>Valor patrimonial</span><span className="metric-icon"><WalletCards size={15} /></span></div><div className="metric-value">{compactBrl(18_500_000)}</div><div className="metric-foot positive">↑ 2,8% última avaliação</div></div><div className="metric-card"><div className="metric-top"><span>Ocupação</span><span className="metric-icon"><Users size={15} /></span></div><div className="metric-value">90,9%</div><div className="metric-foot">20 de 22 unidades</div></div><div className="metric-card"><div className="metric-top"><span>Receita contratada</span><span className="metric-icon">R$</span></div><div className="metric-value">{brl(184_500)}</div><div className="metric-foot positive">89% do potencial</div></div><div className="metric-card"><div className="metric-top"><span>Resultado líquido</span><span className="metric-icon"><ArrowLeft size={15} /></span></div><div className="metric-value">{brl(141_700)}</div><div className="metric-foot">Margem de 76,9%</div></div></section>
    <div className="panel"><div className="panel-heading"><div><h2>Unidades</h2><p>10 de 22 unidades exibidas · filtre por status</p></div><div style={{ display: "flex", gap: 6 }}><button className="button button-primary" style={{ padding: "8px 11px" }}>Todas <span className="tag-count">22</span></button><button className="button button-ghost" style={{ padding: "8px 11px" }}>Alugadas</button><button className="button button-ghost" style={{ padding: "8px 11px" }}>Vagas</button></div></div><div className="table-wrap"><table><thead><tr><th>Unidade</th><th>Tipo / área</th><th>Status</th><th>Aluguel</th><th>Locatário</th><th>Vencimento</th><th /></tr></thead><tbody>{demoUnits.map((unit) => <tr key={unit.id}><td><strong>{unit.code}</strong></td><td><span>{unit.type}</span><small><Ruler size={11} /> {unit.area} m²</small></td><td><span className={`status status-${unit.status}`}>{statusLabel[unit.status]}</span></td><td><strong>{brl(unit.rent)}</strong><small>mensal</small></td><td>{unit.tenant ?? <span className="muted">—</span>}</td><td>{unit.nextDue ?? <span className="muted">—</span>}</td><td><ChevronRight size={15} color="#8490a5" /></td></tr>)}</tbody></table></div></div>
    <div className="wide-grid section-gap"><div className="panel"><div className="panel-heading"><div><h2>Próximos recebimentos</h2><p>Competência setembro 2026</p></div><CalendarDays size={17} color="#8490a5" /></div><div className="payment-line"><div><strong>20 unidades</strong><small>Vencimento até 10/09</small></div><strong className="positive">{brl(184_500)}</strong></div><div className="payment-line"><div><strong>Recebido no mês anterior</strong><small>Agosto 2026</small></div><strong>{brl(176_200)}</strong></div></div><div className="panel"><div className="panel-heading"><div><h2>Saúde do ativo</h2><p>Indicadores operacionais</p></div><BedDouble size={17} color="#8490a5" /></div><div className="health-line"><span>Documentação</span><strong className="positive">Completa</strong></div><div className="health-line"><span>Contratos ativos</span><strong>20 / 22</strong></div><div className="health-line"><span>Inadimplência</span><strong className="positive">0,0%</strong></div></div></div>
  </div>;
}
