import Link from "next/link";
import { Building2, MapPin, Plus, Search, SlidersHorizontal } from "lucide-react";
import { demoBuildings } from "@/lib/demo-data";
import { brl, compactBrl } from "@/lib/format";

export default function ImoveisPage() {
  return <div className="content"><div className="page-heading"><div><div className="eyebrow"><Building2 size={13} /> Portfólio imobiliário</div><h1>Imóveis</h1><p className="subtitle">Acompanhe prédios, unidades e rentabilidade em um só lugar.</p></div><Link href="/onboarding" className="button button-primary"><Plus size={15} /><span>Novo imóvel</span></Link></div>
    <div className="metrics"><div className="metric-card"><div className="metric-top"><span>Patrimônio imobiliário</span><span className="metric-icon"><Building2 size={15} /></span></div><div className="metric-value">{compactBrl(35_800_000)}</div><div className="metric-foot positive">↑ 6,4% este ano</div></div><div className="metric-card"><div className="metric-top"><span>Prédios</span><span className="metric-icon">03</span></div><div className="metric-value">03</div><div className="metric-foot">31 unidades no total</div></div><div className="metric-card"><div className="metric-top"><span>Receita potencial</span><span className="metric-icon">R$</span></div><div className="metric-value">{brl(367_500)}</div><div className="metric-foot positive">91% contratada</div></div><div className="metric-card"><div className="metric-top"><span>Yield médio</span><span className="metric-icon">%</span></div><div className="metric-value">9,8%</div><div className="metric-foot positive">↑ 0,6 p.p. vs. 2025</div></div></div>
    <div className="panel"><div className="panel-heading"><div><h2>Todos os prédios</h2><p>3 ativos · atualização em tempo real</p></div><div style={{ display: "flex", gap: 8 }}><button className="button button-ghost"><Search size={14} /> Buscar</button><button className="button button-ghost"><SlidersHorizontal size={14} /> Filtros</button></div></div><div className="building-list">{demoBuildings.map((building) => <Link href={`/imoveis/${building.id}`} key={building.id} className="building-row" style={{ padding: 16 }}><div className="building-thumb" style={{ width: 62, height: 62 }} /><div className="building-info"><strong style={{ fontSize: 14 }}>{building.name}</strong><small><MapPin size={11} style={{ verticalAlign: "-2px" }} /> {building.city}, {building.state} · Atualizado hoje</small><div style={{ display: "flex", gap: 8, marginTop: 10 }}><span className="tag">{building.status}</span><span className="tag">{building.units} unidades</span></div></div><div className="building-value"><strong style={{ fontSize: 15 }}>{compactBrl(building.value)}</strong><small>{brl(building.revenue)} / mês</small><div style={{ marginTop: 9, width: 100 }}><div className="progress"><span style={{ width: `${(building.occupied / building.units) * 100}%` }} /></div></div></div></Link>)}</div></div>
  </div>;
}
