"use client";

import { ArrowDownRight, ArrowUpRight, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, Edit3, Receipt, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { usePortfolio } from "@/components/portfolio-provider";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { brl } from "@/lib/format";
import { currentMonthKey, monthLabel, shiftMonth } from "@/lib/month";

type Credit = { id: string; value: number; revenue_date: string; competence: string; description: string; origin?: string | null; source_payment_id?: string | null; source_sale_id?: string | null; beneficiary_user_id?: string | null; beneficiary_contact_id?: string | null; recurring?: boolean | null };
type Beneficiary = { member_id: string; user_id?: string | null; contact_id?: string | null; full_name: string; email?: string | null };
type CreditForm = { value: string; description: string; beneficiary: string; recurring: boolean; competence: string };
type MemberSummary = { rentalIncome: number; individualCredits: number; ownExpenses: number; holdingExpenses: number; netTotal: number; credits: Array<{ id: string; value: number; description: string; type: string; recurring?: boolean }>; expenses: Array<{ id: string; description: string; category?: string; value: number; scope: "individual" | "holding" }> };

const emptyCreditForm: CreditForm = { value: "", description: "", beneficiary: "", recurring: false, competence: currentMonthKey() };
const readableError = (error: { message?: string } | null, fallback: string) => {
  const raw = error?.message ?? "";
  if (/automatic_credit_competence_locked/i.test(raw)) return "A competência de um aluguel automático não pode ser alterada; edite o recebimento na aba Aluguéis.";
  if (/automatic_sale_credit_delete_not_allowed/i.test(raw)) return "O crédito de uma venda deve ser ajustado pelo registro da venda.";
  if (/function .*credit|does not exist|schema cache/i.test(raw)) return "A atualização do banco para edição de créditos ainda não foi aplicada.";
  if (/not_authorized|permission/i.test(raw)) return "Sua conta não tem permissão para alterar créditos nesta holding.";
  return raw || fallback;
};

function MonthNavigator({ month, onChange }: { month: string; onChange: (month: string) => void }) { return <div className="month-navigator"><button type="button" className="icon-btn" onClick={() => onChange(shiftMonth(month, -1))} aria-label="Mês anterior"><ChevronLeft size={16} /></button><CalendarDays size={15} /><strong>{monthLabel(month)}</strong><button type="button" className="icon-btn" onClick={() => onChange(shiftMonth(month, 1))} aria-label="Próximo mês"><ChevronRight size={16} /></button></div>; }

export default function CreditosPage() {
  const { organizationId, role, loading } = usePortfolio();
  const [credits, setCredits] = useState<Credit[]>([]); const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]); const [memberSummary, setMemberSummary] = useState<MemberSummary | null>(null); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<Credit | null>(null); const [saving, setSaving] = useState(false); const [summaryLoading, setSummaryLoading] = useState(false); const [message, setMessage] = useState(""); const [selectedMonth, setSelectedMonth] = useState(currentMonthKey); const [form, setForm] = useState<CreditForm>(emptyCreditForm); const [editForm, setEditForm] = useState<CreditForm>(emptyCreditForm);
  const canManage = role === "owner" || role === "admin" || role === "manager";
  const loadCredits = useCallback(async () => { if (!organizationId || !canManage) return; const supabase = createSupabaseBrowserClient(); if (!supabase) return; const result = await supabase.from("revenues").select("id,value,revenue_date,competence,description,origin,source_payment_id,source_sale_id,beneficiary_user_id,beneficiary_contact_id,recurring").eq("organization_id", organizationId).order("revenue_date", { ascending: false }); if (result.error) setMessage(readableError(result.error, "Não foi possível carregar os créditos.")); else setCredits((result.data ?? []) as Credit[]); }, [organizationId, canManage]);
  const loadMemberSummary = useCallback(async () => { if (!organizationId || role !== "viewer") return; const supabase = createSupabaseBrowserClient(); if (!supabase) return; setSummaryLoading(true); const [summaryResult, creditResult, expenseResult] = await Promise.all([supabase.rpc("get_member_revenue_summary", { target_org: organizationId, target_competence: `${selectedMonth}-01` }), supabase.rpc("list_member_credits", { target_org: organizationId, target_competence: `${selectedMonth}-01` }), supabase.rpc("list_member_expenses", { target_org: organizationId })]); if (summaryResult.error) setMessage(readableError(summaryResult.error, "Não foi possível carregar sua receita.")); else { const summary = (summaryResult.data ?? {}) as Record<string, unknown>; const rentalRows = (summary.rentalCredits ?? []) as Array<Record<string, unknown>>; const creditRows = (creditResult.data ?? []) as Array<Record<string, unknown>>; const expenseRows = (expenseResult.data ?? []) as Array<Record<string, unknown>>; const periodExpenses = expenseRows.filter((expense) => String(expense.expense_kind ?? "recurring") !== "one_time" || String(expense.expense_date ?? "").startsWith(selectedMonth)); setMemberSummary({ rentalIncome: Number(summary.rentalIncome ?? 0), individualCredits: Number(summary.individualCredits ?? 0), ownExpenses: Number(summary.ownExpenses ?? 0), holdingExpenses: Number(summary.holdingExpenses ?? 0), netTotal: Number(summary.netTotal ?? 0), credits: [...rentalRows.map((credit) => ({ id: `rent-${String(credit.id)}`, value: Number(credit.value ?? 0), description: String(credit.description ?? "Imóvel"), type: "Aluguel", recurring: false })), ...creditRows.map((credit) => ({ id: String(credit.id), value: Number(credit.value ?? 0), description: String(credit.description ?? "Pagamento individual"), type: credit.recurring ? "Pagamento recorrente" : "Pagamento individual", recurring: Boolean(credit.recurring) }))], expenses: periodExpenses.filter((expense) => Number(expense.member_share ?? expense.value ?? 0) > 0).map((expense) => ({ id: String(expense.id), description: String(expense.description ?? "Despesa"), category: expense.category ? String(expense.category) : undefined, value: Number(expense.member_share ?? expense.value ?? 0), scope: Boolean(expense.is_holding_expense) ? "holding" : "individual" })) }); } setSummaryLoading(false); }, [organizationId, role, selectedMonth]);
  useEffect(() => { void loadCredits(); }, [loadCredits]); useEffect(() => { void loadMemberSummary(); }, [loadMemberSummary]);
  useEffect(() => { if (!organizationId || !canManage) return; const supabase = createSupabaseBrowserClient(); if (!supabase) return; supabase.rpc("list_organization_members", { target_org: organizationId }).then(({ data, error }) => { if (!error) setBeneficiaries((data ?? []) as Beneficiary[]); }); }, [organizationId, canManage]);
  async function createCredit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organizationId || !form.value || !form.description.trim() || !form.beneficiary) { setMessage("Informe valor, descrição e beneficiário."); return; } const value = Number(form.value.replace(",", ".")); if (!Number.isFinite(value) || value <= 0) { setMessage("Informe um valor válido para o crédito."); return; } const person = beneficiaries.find((item) => item.member_id === form.beneficiary); if (!person) { setMessage("Selecione um beneficiário válido."); return; } const supabase = createSupabaseBrowserClient(); if (!supabase) return; setSaving(true); setMessage(""); const result = await supabase.rpc("create_individual_credit", { target_org: organizationId, target_value: value, target_competence: `${selectedMonth}-01`, target_description: form.description.trim(), target_beneficiary_user: person.user_id ?? null, target_beneficiary_contact: person.contact_id ?? null, target_recurring: form.recurring }); if (result.error) setMessage(readableError(result.error, "Não foi possível criar o crédito individual.")); else { setForm({ ...emptyCreditForm, competence: selectedMonth }); setCreating(false); setMessage("Pagamento individual criado e debitado do saldo da holding."); await loadCredits(); } setSaving(false); }
  function beginEdit(credit: Credit) { setEditing(credit); setMessage(""); setEditForm({ value: String(credit.value ?? ""), description: credit.description ?? "", beneficiary: "", recurring: Boolean(credit.recurring), competence: (credit.competence || credit.revenue_date || selectedMonth).slice(0, 7) }); }
  async function saveCredit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organizationId || !editing) return; const value = Number(editForm.value.replace(",", ".")); if (!Number.isFinite(value) || value <= 0 || !editForm.description.trim()) { setMessage("Informe um valor e uma descrição válidos."); return; } const supabase = createSupabaseBrowserClient(); if (!supabase) return; setSaving(true); setMessage(""); const result = await supabase.rpc("update_credit", { target_org: organizationId, target_credit: editing.id, target_value: value, target_description: editForm.description.trim(), target_competence: `${editForm.competence}-01`, target_recurring: editing.origin === "individual_benefit" ? editForm.recurring : null }); if (result.error) setMessage(readableError(result.error, "Não foi possível editar o crédito.")); else { setEditing(null); setMessage("Crédito atualizado e saldo sincronizado."); await loadCredits(); } setSaving(false); }
  async function deleteCredit(credit: Credit) { if (!organizationId || !window.confirm(`Excluir o crédito “${credit.description}”? Essa ação também desfaz o pagamento automático, quando houver.`)) return; const supabase = createSupabaseBrowserClient(); if (!supabase) return; setSaving(true); setMessage(""); const result = await supabase.rpc("delete_credit", { target_org: organizationId, target_credit: credit.id }); if (result.error) setMessage(readableError(result.error, "Não foi possível excluir o crédito.")); else { setMessage("Crédito excluído e saldo sincronizado."); await loadCredits(); } setSaving(false); }
  const visibleCredits = useMemo(() => credits.filter((credit) => { const date = credit.competence || credit.revenue_date; return Boolean(date?.startsWith(selectedMonth) || (credit.recurring && credit.revenue_date && credit.revenue_date <= `${selectedMonth}-31`)); }), [credits, selectedMonth]);
  if (loading) return <div className="content"><div className="empty-state"><p>Carregando créditos...</p></div></div>; if (!organizationId) return <div className="content"><div className="empty-state"><CircleDollarSign size={28} /><h3>Nenhuma holding selecionada</h3></div></div>; if (role === "viewer") return <MemberRevenueView summary={memberSummary} loading={summaryLoading} month={selectedMonth} onMonthChange={setSelectedMonth} message={message} />;
  return <AdminCredits message={message} setMessage={setMessage} selectedMonth={selectedMonth} setSelectedMonth={setSelectedMonth} canManage={canManage} creating={creating} setCreating={setCreating} form={form} setForm={setForm} saving={saving} createCredit={createCredit} visibleCredits={visibleCredits} beneficiaries={beneficiaries} editing={editing} editForm={editForm} setEditForm={setEditForm} saveCredit={saveCredit} setEditing={setEditing} beginEdit={beginEdit} deleteCredit={deleteCredit} />;
}

function AdminCredits({ message, setMessage, selectedMonth, setSelectedMonth, canManage, creating, setCreating, form, setForm, saving, createCredit, visibleCredits, beneficiaries, editing, editForm, setEditForm, saveCredit, setEditing, beginEdit, deleteCredit }: { message: string; setMessage: (value: string) => void; selectedMonth: string; setSelectedMonth: (value: string) => void; canManage: boolean; creating: boolean; setCreating: (value: boolean) => void; form: CreditForm; setForm: React.Dispatch<React.SetStateAction<CreditForm>>; saving: boolean; createCredit: (event: React.FormEvent<HTMLFormElement>) => void; visibleCredits: Credit[]; beneficiaries: Beneficiary[]; editing: Credit | null; editForm: CreditForm; setEditForm: React.Dispatch<React.SetStateAction<CreditForm>>; saveCredit: (event: React.FormEvent<HTMLFormElement>) => void; setEditing: (value: Credit | null) => void; beginEdit: (credit: Credit) => void; deleteCredit: (credit: Credit) => void }) {
  const holdingCredits = visibleCredits.filter((credit) => credit.origin !== "individual_benefit"); const individualCredits = visibleCredits.filter((credit) => credit.origin === "individual_benefit"); const holdingTotal = holdingCredits.reduce((sum, credit) => sum + Number(credit.value || 0), 0); const individualTotal = individualCredits.reduce((sum, credit) => sum + Number(credit.value || 0), 0);
  return <div className="content"><div className="page-heading"><div><div className="eyebrow"><ArrowUpRight size={13} /> Entradas e pagamentos</div><h1>Créditos</h1><p className="subtitle">Entradas da holding separadas dos pagamentos individuais aos membros.</p></div><div className="page-heading-actions"><MonthNavigator month={selectedMonth} onChange={setSelectedMonth} />{canManage && <button type="button" className="button button-primary" onClick={() => { setCreating(true); setMessage(""); }}><ArrowDownRight size={14} /> Pagamento individual</button>}</div></div>{message && <p className={message.includes("não") || message.includes("Não") || message.includes("Informe") || message.includes("permissão") ? "form-error" : "form-success"}><CheckCircle2 size={13} /> {message}</p>}
    {creating && <CreditFormPanel title="Novo pagamento individual" subtitle={`Competência: ${monthLabel(selectedMonth)} · será debitado do saldo da holding.`} form={form} setForm={setForm} beneficiaries={beneficiaries} saving={saving} onSubmit={createCredit} onClose={() => { setCreating(false); setForm({ ...emptyCreditForm, competence: selectedMonth }); }} submitLabel="Criar pagamento" />}
    {editing && <CreditFormPanel title="Editar crédito" subtitle={editing.origin === "individual_benefit" ? "Pagamento individual: altera o valor debitado e o benefício do membro." : "Crédito automático: altera o valor sincronizado com o recebimento."} form={editForm} setForm={setEditForm} beneficiaries={beneficiaries} saving={saving} onSubmit={saveCredit} onClose={() => setEditing(null)} submitLabel="Salvar alterações" editMode origin={editing.origin} />}
    <div className="metrics"><Metric title={`Entradas da holding · ${monthLabel(selectedMonth)}`} value={holdingTotal} foot="Aluguéis, vendas e outras entradas" icon={<ArrowUpRight size={15} />} /><Metric title="Pagamentos individuais" value={-individualTotal} foot="Débitos destinados a membros" icon={<ArrowDownRight size={15} />} negative /><Metric title="Lançamentos" value={visibleCredits.length} foot={`Competência de ${monthLabel(selectedMonth)}`} icon={<Receipt size={15} />} count /></div>
    <div className="panel"><div className="panel-heading"><div><h2>Movimentações de {monthLabel(selectedMonth)}</h2><p>Créditos automáticos entram no saldo; pagamentos individuais saem do saldo e vão para o beneficiário.</p></div></div>{visibleCredits.length ? <div className="table-wrap"><table><thead><tr><th>Descrição</th><th>Beneficiário</th><th>Competência</th><th>Natureza</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{visibleCredits.map((credit) => { const person = beneficiaries.find((item) => (credit.beneficiary_user_id != null && item.user_id === credit.beneficiary_user_id) || (credit.beneficiary_contact_id != null && item.contact_id === credit.beneficiary_contact_id)); const individual = credit.origin === "individual_benefit"; return <tr key={credit.id}><td><strong>{credit.description}</strong>{credit.source_payment_id && <small>Pagamento de aluguel</small>}{credit.source_sale_id && <small>Venda confirmada</small>}{credit.recurring && <small>Recorrente</small>}</td><td>{person?.full_name ?? (individual ? "Beneficiário individual" : "—")}</td><td>{credit.competence ? new Date(`${credit.competence}T12:00:00`).toLocaleDateString("pt-BR") : "—"}</td><td><span className={`tag ${individual ? "negative" : "positive"}`}>{individual ? "Pagamento individual" : credit.origin === "lease_payment" ? "Aluguel" : credit.origin === "property_sale" ? "Venda" : "Entrada"}</span></td><td className={individual ? "negative" : "positive"}><strong>{brl(individual ? -Number(credit.value || 0) : Number(credit.value || 0))}</strong></td><td><div className="table-actions">{canManage && <><button type="button" className="icon-btn" onClick={() => beginEdit(credit)} disabled={saving} aria-label={`Editar ${credit.description}`}><Edit3 size={14} /></button><button type="button" className="icon-btn danger-button" onClick={() => void deleteCredit(credit)} disabled={saving || Boolean(credit.source_sale_id)} aria-label={`Excluir ${credit.description}`}><Trash2 size={14} /></button></>}</div></td></tr>; })}</tbody></table></div> : <div className="empty-state"><CircleDollarSign size={28} /><h3>Nenhuma movimentação registrada</h3><p>Confirme um aluguel ou crie um pagamento individual.</p></div>}</div></div>;
}

function CreditFormPanel({ title, subtitle, form, setForm, beneficiaries, saving, onSubmit, onClose, submitLabel, editMode, origin }: { title: string; subtitle: string; form: CreditForm; setForm: React.Dispatch<React.SetStateAction<CreditForm>>; beneficiaries: Beneficiary[]; saving: boolean; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onClose: () => void; submitLabel: string; editMode?: boolean; origin?: string | null }) {
  const individual = origin === "individual_benefit" || !editMode;
  return <div className="panel"><form onSubmit={onSubmit}><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Fechar">×</button></div><div className="form-grid">{individual && <label>Beneficiário<select value={form.beneficiary} onChange={(event) => setForm((current) => ({ ...current, beneficiary: event.target.value }))} disabled={editMode}><option value="">Selecione uma pessoa</option>{beneficiaries.map((person) => <option value={person.member_id} key={person.member_id}>{person.full_name}{person.email ? ` · ${person.email}` : ""}</option>)}</select></label>}<label>Valor<input type="number" min="0.01" step="0.01" value={form.value} onChange={(event) => setForm((current) => ({ ...current, value: event.target.value }))} placeholder="0,00" required /></label><label>Competência<input type="month" value={form.competence} onChange={(event) => setForm((current) => ({ ...current, competence: event.target.value }))} disabled={editMode && !individual} required /></label><label style={{ gridColumn: "1 / -1" }}>Descrição<input value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} placeholder="Ex.: benefício, reembolso ou bonificação" required /></label>{individual && <label className="checkbox-field form-grid-wide"><input type="checkbox" checked={form.recurring} onChange={(event) => setForm((current) => ({ ...current, recurring: event.target.checked }))} disabled={editMode === true && origin !== "individual_benefit"} /> Pagamento recorrente</label>}</div><div className="onboarding-actions"><button type="button" className="button button-ghost" onClick={onClose}>Cancelar</button><button type="submit" className="button button-primary" disabled={saving}>{saving ? "Salvando…" : submitLabel}</button></div></form></div>;
}

function MemberRevenueView({ summary, loading, month, onMonthChange, message }: { summary: MemberSummary | null; loading: boolean; month: string; onMonthChange: (value: string) => void; message: string }) { const data = summary ?? { rentalIncome: 0, individualCredits: 0, ownExpenses: 0, holdingExpenses: 0, netTotal: 0, credits: [], expenses: [] }; return <div className="content"><div className="page-heading"><div><div className="eyebrow"><ArrowUpRight size={13} /> Receita do membro</div><h1>Créditos e receita</h1><p className="subtitle">Sua visão individual de {monthLabel(month)}.</p></div><MonthNavigator month={month} onChange={onMonthChange} /></div>{message && <p className="form-error"><CheckCircle2 size={13} /> {message}</p>}{loading ? <div className="empty-state"><p>Carregando sua receita…</p></div> : <><div className="metrics member-revenue-metrics"><Metric title="Aluguéis pagos" value={data.rentalIncome} foot="Sua parcela somente dos pagamentos confirmados" icon={<ArrowUpRight size={15} />} /><Metric title="Pagamentos individuais" value={data.individualCredits} foot="Benefícios destinados a você" icon="R$" /><Metric title="Despesas individuais" value={data.ownExpenses} foot="Sua responsabilidade" icon={<ArrowDownRight size={15} />} negative /><Metric title="Despesas da holding" value={data.holdingExpenses} foot="Sua cota proporcional" icon={<Receipt size={15} />} negative /><Metric title="Resultado líquido" value={data.netTotal} foot="Receitas + pagamentos − despesas" icon="R$" negative={data.netTotal < 0} /></div><div className="dashboard-grid"><MemberTable title={`Créditos do mês · ${monthLabel(month)}`} note="Aluguéis pagos, pró-labore e outros pagamentos destinados a você." empty="Nenhum crédito registrado neste mês." rows={data.credits.map((credit) => <tr key={credit.id}><td><strong>{credit.description}</strong>{credit.recurring && <small>Recorrente</small>}</td><td>{credit.type}</td><td className="positive"><strong>{brl(Number(credit.value || 0))}</strong></td></tr>)} headers={["Descrição", "Tipo", "Valor"]} /><MemberTable title="Despesas consideradas" note="Somente suas responsabilidades e a cota das despesas gerais." empty="Nenhuma despesa considerada neste mês." rows={data.expenses.map((expense) => <tr key={expense.id}><td><strong>{expense.description}</strong><small>{expense.category || "Operacional"}</small></td><td><span className="tag">{expense.scope === "holding" ? "Holding" : "Sua responsabilidade"}</span></td><td className="negative"><strong>{brl(Number(expense.value || 0))}</strong></td></tr>)} headers={["Descrição", "Responsabilidade", "Valor"]} /></div></>}</div>; }
function Metric({ title, value, foot, icon, negative, count }: { title: string; value: number; foot: string; icon: React.ReactNode; negative?: boolean; count?: boolean }) { return <div className="metric-card"><div className="metric-top"><span>{title}</span><span className="metric-icon">{icon}</span></div><div className={`metric-value ${negative ? "negative" : ""}`}>{count ? value : brl(value)}</div><div className="metric-foot">{foot}</div></div>; }
function MemberTable({ title, note, empty, rows, headers }: { title: string; note: string; empty: string; rows: React.ReactNode[]; headers: string[] }) { return <div className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{note}</p></div></div>{rows.length ? <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows}</tbody></table></div> : <div className="empty-state" style={{ minHeight: 110 }}><p>{empty}</p></div>}</div>; }
