import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Download, Plus, Receipt } from "lucide-react";
import { initialProperties } from "@/lib/initial-property-data";
import { brl } from "@/lib/format";

export default function FinanceiroPage() {
  const rentalProperties = initialProperties.filter((property) => property.rent !== undefined);
  const monthlyRent = rentalProperties.reduce((total, property) => total + (property.rent ?? 0), 0);
  const rentedUnits = rentalProperties.reduce((total, property) => total + (property.unitCount ?? 1), 0);
  return <div className="content"><div className="page-heading"><div><div className="eyebrow"><CircleDollarSign size={13} /> Fluxo financeiro</div><h1>Financeiro</h1><p className="subtitle">Receitas exclusivamente dos aluguéis informados na planilha.</p></div><div style={{ display: "flex", gap: 8 }}><button className="button button-ghost"><Download size={14} /> Exportar</button><button className="button button-primary"><Plus size={15} /> Novo lançamento</button></div></div>
    <div className="metrics"><div className="metric-card"><div className="metric-top"><span>Aluguéis mensais informados</span><span className="metric-icon"><ArrowUpRight size={15} /></span></div><div className="metric-value">{brl(monthlyRent)}</div><div className="metric-foot positive">{rentedUnits} unidades com aluguel</div></div><div className="metric-card"><div className="metric-top"><span>Despesas cadastradas</span><span className="metric-icon"><ArrowDownRight size={15} /></span></div><div className="metric-value">{brl(0)}</div><div className="metric-foot">Nenhuma na planilha</div></div><div className="metric-card"><div className="metric-top"><span>Resultado informado</span><span className="metric-icon">%</span></div><div className="metric-value">{brl(monthlyRent)}</div><div className="metric-foot">Antes de despesas</div></div><div className="metric-card"><div className="metric-top"><span>Histórico de recebimento</span><span className="metric-icon"><Receipt size={15} /></span></div><div className="metric-value">—</div><div className="metric-foot">Datas não informadas</div></div></div>
    <div className="panel"><div className="panel-heading"><div><h2>Aluguéis informados</h2><p>{rentalProperties.length} registros com valor mensal · origem: dados imoveis.xlsx</p></div><button className="button button-ghost">Ver todos</button></div><div className="table-wrap"><table><thead><tr><th>Imóvel / unidade</th><th>Localidade</th><th>Status na planilha</th><th>Valor mensal</th></tr></thead><tbody>{rentalProperties.map((property) => <tr key={property.id}><td><strong>{property.unitCode}</strong><small>{property.buildingName}</small></td><td>{property.city} · {property.uf || "—"}</td><td><span className="status status-alugado">Alugado</span></td><td className="positive"><strong>{brl(property.rent ?? 0)}</strong></td></tr>)}</tbody></table></div></div>
  </div>;
}
